services:
  - docker

jobs:
  include:
    - stage: deploy
      if: branch = master AND type = push
      name: "Build image and upload to Docker Hub"
      script:
        # this task takes very long to complete
        - travis_wait 120 make docker-image
      after_success:
        - make docker-upload || travis_terminate 1
    - stage: test
      name: "Test Pandas"
      script: make docker-test
